name: Main

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cargo
        with:
          components: rustfmt, clippy
      - run: cargo test --all --release

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cargo
      - name: Install trunk
        run: cargo install trunk
      - name: Build
        run: cd cumulo-web && trunk build --release --public-url /cumulo/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/trunk

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 30
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
